name: Add issues to project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e
        with:
          # You can target a project in a different organization or user account
          # to the issue.
          # For organization projects: https://github.com/orgs/ORG_NAME/projects/PROJECT_NUMBER
          # For user projects: https://github.com/users/USER_NAME/projects/PROJECT_NUMBER
          project-url: https://github.com/orgs/childrens-bti/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
